// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKybkKTjRs6qFjE__s1xJwrChR0SErXPk',
    appId: '1:86207064073:web:6e6dd93d9bc14088f530d8',
    messagingSenderId: '86207064073',
    projectId: 'stepwars-35179',
    authDomain: 'stepwars-35179.firebaseapp.com',
    storageBucket: 'stepwars-35179.firebasestorage.app',
    measurementId: 'G-G2V5NEQJ4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsb_qtoB9EsRCzLXA_cWYAJAUuOLODhVc',
    appId: '1:86207064073:android:91bbc6d147ab2a4ef530d8',
    messagingSenderId: '86207064073',
    projectId: 'stepwars-35179',
    storageBucket: 'stepwars-35179.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWiH1U0js7jNnjsYop_TawvwRVMWcVxVI',
    appId: '1:86207064073:ios:cd1e3d0cba1c8e8bf530d8',
    messagingSenderId: '86207064073',
    projectId: 'stepwars-35179',
    storageBucket: 'stepwars-35179.firebasestorage.app',
    iosBundleId: 'com.example.stepwarsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWiH1U0js7jNnjsYop_TawvwRVMWcVxVI',
    appId: '1:86207064073:ios:cd1e3d0cba1c8e8bf530d8',
    messagingSenderId: '86207064073',
    projectId: 'stepwars-35179',
    storageBucket: 'stepwars-35179.firebasestorage.app',
    iosBundleId: 'com.example.stepwarsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKybkKTjRs6qFjE__s1xJwrChR0SErXPk',
    appId: '1:86207064073:web:46b0b9df622a2bd3f530d8',
    messagingSenderId: '86207064073',
    projectId: 'stepwars-35179',
    authDomain: 'stepwars-35179.firebaseapp.com',
    storageBucket: 'stepwars-35179.firebasestorage.app',
    measurementId: 'G-GPFWWFDEBS',
  );
}
