// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-2bphSFlpzOliyg_wDt00hubL5jMGzus',
    appId: '1:955460127665:web:7144a2cfb99f911d228b90',
    messagingSenderId: '955460127665',
    projectId: 'stepwarsnew',
    authDomain: 'stepwarsnew.firebaseapp.com',
    databaseURL: 'https://stepwarsnew-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stepwarsnew.firebasestorage.app',
    measurementId: 'G-5JLBKH1DQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATfJVT60JPNN8u_LTKjV1eCzso09Qe68I',
    appId: '1:955460127665:android:d152f69cfeeb9366228b90',
    messagingSenderId: '955460127665',
    projectId: 'stepwarsnew',
    databaseURL: 'https://stepwarsnew-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stepwarsnew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtpISUwMVgMX_s2OFcXcqyrGZTGifuYac',
    appId: '1:955460127665:ios:993de77e76b31847228b90',
    messagingSenderId: '955460127665',
    projectId: 'stepwarsnew',
    databaseURL: 'https://stepwarsnew-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stepwarsnew.firebasestorage.app',
    androidClientId: '955460127665-6brdoj3j6sqs87ia8lpfi29l6g37s1v9.apps.googleusercontent.com',
    iosClientId: '955460127665-gvlrvslqs49mt9k256lonsbvhamvgu2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepwarsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtpISUwMVgMX_s2OFcXcqyrGZTGifuYac',
    appId: '1:955460127665:ios:993de77e76b31847228b90',
    messagingSenderId: '955460127665',
    projectId: 'stepwarsnew',
    databaseURL: 'https://stepwarsnew-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stepwarsnew.firebasestorage.app',
    androidClientId: '955460127665-6brdoj3j6sqs87ia8lpfi29l6g37s1v9.apps.googleusercontent.com',
    iosClientId: '955460127665-gvlrvslqs49mt9k256lonsbvhamvgu2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepwarsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-2bphSFlpzOliyg_wDt00hubL5jMGzus',
    appId: '1:955460127665:web:722f48ec12976cbf228b90',
    messagingSenderId: '955460127665',
    projectId: 'stepwarsnew',
    authDomain: 'stepwarsnew.firebaseapp.com',
    databaseURL: 'https://stepwarsnew-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stepwarsnew.firebasestorage.app',
    measurementId: 'G-QVSJYNPZE6',
  );

}